### ISSUE TITLE
Umlauts weren't displayed

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#31]
The font you use don't have umlauts like "ä,Ä,üÜ" can you take a other fond?

**Comment by peepshow-21** [comment]
I am open to changing the font to one that works better for EU users.
Currently, it's using Calibri, which I just picked because it looks good.

That doesn't have those characters?

[image: image.png]

Can you check they are missing from the font, and it's not a Nextion issue?

Font suggestions welcome. So long as looks good and pretty clean and
modern, I could look at that.

**Comment by viper-666** [comment]
Is isn't a font problem, also the console can display umlauts so I think it has to do with the nexion display, a short search says it uses ASCII for the seriell port so it will be hard to implement that.

**Comment by peepshow-21** [comment]
try the latest nxpanel.be to see if that helps.

**Comment by peepshow-21** [comment]
https://theasciicode.com.ar/extended-ascii-code/degree-symbol-ascii-code-248.html
They seem to be in standard ascii
someone complained the “18.5°C” degree sign didnt work. that is 0xB0. but the backend seems to expand those and out 0xC2B0... I changed the berry to strip the C2 before sending to nextion and it worked for the degree. But it doesnt seem the same the umlauts .. I tried. might not be worth giving up yet. They just might not be in the first 256 char of that font. I've no time but you could dig more. print the first 256 char on that font and see what's there.
