### ISSUE TITLE
Warnings icon state: 0 don't work

### ISSUE THREAD

**Issue by viper-666** [peepshow-21/ns-flash#44]
What should the "state":0 command do? If I send:
`nxpanel {"warnings":[{"id":2,"type":2,"state":0}]}} `
The icon with the three blue arrows appears the house what was before on this place is gone.

**Comment by peepshow-21** [comment]
type:0 is invisiable, state is ignored

and it;s notification*S* not notification. which is why they were not
showing.

to add more colors would be a pain as it means2 more garphics per item and
they would all need moved, as it'd caluclaued by icon id x 3 now.

adding new ones, is not so bad. more of the same, more work. it's
possilble, but right now too much with with all the rest that needs
finished.
